function [AutomaticEvents,ManualEvents] = NLX_ReadEventFile(FName)
% Reads the event file 'Events.Nev' for neuralynx analysis and return two lists.
% One contaning all the automaticly generated events that Neuralynx saves
% whenever it recives a TTL signal from cortec. And one contaning all the
% events generated by the user manually entering events in Neuralynx.
% All automatic events with the TTL code of 0 is removed since they are
% used as resets and don't actually encode anything.
%
% Input:
%  FName : Filename of a neuralynx events file (.nev)
%
% Output:
%  AutomaticEvents :    array of automaticly generated events consisting of a
%                       timestamp and TTL code
%  ManualEvents:        CELL array containing timestamp, event_ID and EventString
%



% If no filename is supplied, ask for one
 if nargin<1 || isempty(FName);
    [fileName,filePath] = uigetfile('*.*','open a Event.Nev data file','MultiSelect','off'); 
    FName = fullfile(filePath,fileName);
 end

if ~exist(FName,'file')
    error('FileChk:FileNotFound',['Event file not found: ',FName]);
end
 
% Read the file
[TimeStamps, event_ID, Nttls, EventStrings, ~] = Nlx2MatEV( FName, [1 1 1 0 1],1,1,1); % [TimeStamps, EventIDs, Nttls, Extras, EventStrings, Header]

% Timestamps : the time of the event in NLX time
% EventIDs : Type of event, is 0 for all automatic events and 4 for manual
% Nttls : Neuralynx TTL signal, code sent from cortex
% Extras : Codes that can be assigned later never used until now
% EventStrings : Cell contaning the original saved string
% Header : The header from the NEV file

% rotate the data arrays
TimeStamps = TimeStamps';
event_ID = event_ID';
Nttls = Nttls';

%% work on the automatic data (Events generated by Neuralynx)
Automatic = (event_ID==0); % select all automatic events
Data = [TimeStamps,event_ID,Nttls]; % combine data into one array
AutomaticEvents = Data(Automatic,[1,3]); % Extract all automatic events
ZeroEvents = (AutomaticEvents(:,2)==0); % Select all event that has 0 as the TTL code
AutomaticEvents = AutomaticEvents(~ZeroEvents,:); % Remove all zero events

%% Work on the manual data (Events enerated by manually entering events);
ManData = Data(~Automatic,1:2);  % Get all events that are not automatic
ManualEvents = num2cell(ManData); % Convert them to cells so we can add the strings
ManualStr = EventStrings(~Automatic); % Select the coresponding strings
ManualEvents = [ManualEvents,ManualStr]; % combine them in one cell array


